POST http://localhost:8080/login
Content-Type: application/json

{
  "email": "test@localhost.local"
}

###
POST http://localhost:8080/register
Content-Type: application/json

{
  "email": "test@localhost.local",
  "callback": "http://localhost:8001/callback"
}